version: '3.4'
services:
  iac:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - C:/Docker_File_Sharing/project-folder/.aws/:/root/.aws
      - C:/Docker_File_Sharing/project-folder/.ssh:/root/.ssh/
      - C:/Docker_File_Sharing/project-folder:/project-folder
